govuk-one-login/life-events-platform

- terraform/demo/main.tf
- terraform/dev/main.tf
- terraform/modules/lev_api/main.tf
- terraform/modules/lev_api/outputs.tf
Should pull down the lev api from quay.
By setting the "MOCK" flag we can avoid having to do much more in terms of database setup.
resolves #21
> feat: add lev api app runner

- terraform/demo/main.tf
- terraform/dev/main.tf
- terraform/modules/ecr/ecr.tf
- terraform/modules/lev_api/main.tf
- terraform/modules/lev_api/variables.tf
- isn't abailable in eu-west-2, so this adds an eu-west-1 provider
- ensure the lev service is proxied correctly in ECR
> feat: Update AppRunner configuration

- src/main/resources/application.yml
- terraform/modules/cognito/main.tf
- terraform/modules/data-share-service/ecs.tf
The swagger ui auto generates a URL that has http in it, which doesn't work or make much sense, this explicitly sets the redirect url
> feat: Add explicit Swagger UI Oauth redirects

- README.md
- docker-compose-full.yml
- docker-compose.yml
- src/main/kotlin/uk/gov/gdx/datashare/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventDataRetrievalService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/HmrcApiService.kt
- src/main/resources/application-dev.yml
- terraform/modules/data-share-service/ecs.tf
https://github.com/alphagov/gdx-data-share-poc/issues/72
We currently have mock value for `API_BASE_URL_HMRC`, we should figure out a better approach for this.
As we consume from an API directly, the simplest option for POC would be to stub data within the service itself, and not call out to an external endpoint, so we should
remove the config value
generate a NinoRecord programatically from `HmrcApiService`
> Properly configure hmrc url

- src/main/kotlin/uk/gov/gdx/datashare/service/LegacyAdaptorInbound.kt
- terraform/modules/data-share-service/s3.tf
S3 client currently is non function, see #97 
For the moment we are leaving this as it is non blocking
> docs: Add documentation for WIP s3 client work

- build.gradle.kts
- src/main/kotlin/uk/gov/gdx/datashare/config/MicrometerConfiguration.kt
- src/main/kotlin/uk/gov/gdx/datashare/resource/EventListener.kt
- terraform/modules/data-share-service/cloudwatch.tf
Once the application is deployed and running, we'll want to be able to monitor things like queue throughput, availability, latency etc.
CloudWatch has enough tooling to be able to do what we need, and Spring Boot has built in metrics (through Micrometer) which can integrate with CloudWatch.
We should
configure Spring Boot to feed metrics to Cloud Watch - see [Publishing Metrics from Spring Boot to Amazon CloudWatch](https://reflectoring.io/spring-aws-cloudwatch/) for some background, we want to use Micrometer to have a minimal amount of configuration and management
set up a minimal dashboard through terraform
configure at least one metric to ensure it all feeds through - lets use /event-data-receiver for ingested events, incrementing a counter for each call to the API
Later, we'll need to …
> Create metrics dashboard

- build.gradle.kts
- src/main/kotlin/uk/gov/gdx/datashare/queue/AmazonSnsFactory.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/AmazonSqsFactory.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueue.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueDestinationResolver.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueFactory.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueHealth.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueJmsListenerContainerFactory.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueResourceAsync.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueService.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsSqsProperties.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsTopic.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsTopicFactory.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/HmppsTopicHealth.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/QueueConfig.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/AuditService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/DataReceiverService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/DataShareTopicService.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/gdx/datashare/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsNoDlqQueueFactoryTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsNoDlqQueueHealthTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueFactoryTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueHealthTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsQueueServiceTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsSqsPropertiesTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsTopicFactoryTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/HmppsTopicHealthTest.kt
- src/test/resources/application-test.yml
This is a bit of a thinking out loud more than an absolute must, but from the problems we had with ShedLock, I'd be keen to reduce the number of dependencies overall/have control over them, and particularly, have control over things like spring versions.
This is a lift of the bits of the SQS/SNS management that are required for our code to function and no more, and it's not massively complex code in the end either so I think the maintenance burden for us is quite low. I also think there are bits of the HMPPS code that are a useful general solution, but not something I think we really want in their current form (the DLQ retrying stuff for example, I think we want different control over to suit our use cases), so bringing that in to then be editable by us easily seems reasonable.
> chore: Remove HMPPS SQS dependencies

- terraform/modules/data-share-service/rds.tf
Per https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Enabling.html#:~:text=mydbinstance%20%5C%0A%20%20%20%20%2D-,%2Dapply%2Dimmediately,-%5C%0A%20%20%20%20%2D%2Denable%2Diam and https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#:~:text=can%20use%20the-,apply_immediately,-flag%20to%20instruct
> fix: Apply IAM credentials change immediately

- .github/workflows/kotlin-lint-fix.yml
- .github/workflows/terraform-fmt-fix.yml
This makes the Kotlin and TF linters add a commit to a PR with any formatting changes required, hopefully only when you've touched relevant files.
This I think is generally better than just erroring - if it's a style opinion that we can automatically fix, lets do that.
The only relevant file changes (if this PR ends up adding some other files automatically!) are the workflow yml files.
> chore: Make terraform and Kotlin format jobs add commit to a PR

- terraform/modules/data-share-service/ecs.tf
This is more generous than it needs to be because the docs indicate that it will still attempt health checks during this period and the container can become healthy before the startPeriod has elapsed
[If a health check succeeds within the startPeriod, then the container is considered healthy and any subsequent failures count toward the maximum number of retries.](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html#:~:text=If%20a%20health%20check%20succeeds%20within%20the%20startPeriod%2C%20then%20the%20container%20is%20considered%20healthy%20and%20any%20subsequent%20failures%20count%20toward%20the%20maximum%20number%20of%20retries.)
> fix: add startPeriod to healthcheck to allow container time to becom healthy

- src/main/kotlin/uk/gov/gdx/datashare/config/WebClientConfiguration.kt
Aims to prevent connection closed by client errors https://github.com/reactor/reactor-netty/issues/1774
> fix: set connection params for webclient

- terraform/modules/consumer/lambdas/get_events.py
At peak, this will need to fetch around 1500 events given it runs every 30 minutes. A page size of 20 is too low to fetch this many in the 10 second lambda execution limit
> chore: increase get events page size

- src/test/kotlin/uk/gov/gdx/datashare/integration/LocalStackContainer.kt
This is a slightly optimistic thing, but I  think giving LocalStack a couple of attempts to start up seems reasonable
> GPC-69: Retry LocalStack startup to stabilise builds

- Dockerfile
Using ADD here means we don't need to fetch curl every time we do an uncached build and splits the fetch to where it's actually needed
> GPC-152: Use ADD command over curl

- terraform/modules/data-share-service/deploy_hook.tf
- terraform/modules/data-share-service/vpc.tf
This is fine and can access everything in the public subnet. However, the lb has no fixed private IP, so we cannot call it internal to the vpc. We'll need to allow public access on 8080 and do header based auth I think
> GPC-NONE: move deploy hook lambdas to private subnet

- terraform/modules/data-share-service/iam.tf
Not really important in this instance, but more just to point out that there are situations where these get logged out in github actions if we're not careful
> GPC-NONE: Hide ssm param values

- src/main/kotlin/uk/gov/gdx/datashare/services/DeathNotificationService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/EnrichmentService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/EventDataService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/NullEventEnrichmentService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/PrisonerLookupService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/TestEventEnrichmentService.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/DeathNotificationServiceTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/EventDataServiceTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/PrisonerLookupServiceTest.kt
Not sure how everyone feels about this as an approach, but it means adding an event handler is a little easier/doesn't need all the code changes.
If people like it, I'd want to rejig the tests
- each and every event type has exactly one handler
- splitting the aggregation from the event handlers themselves
- testing the aggregation
> GPC-NONE: Restructure event handling

- doc/runbooks/deployment-failures.md
This might be a very wrong thing, but from discussion at planning here's a rough starter
> GPC-82: Add runbook for deployment failures

- src/main/kotlin/uk/gov/gdx/datashare/config/MicrometerConfiguration.kt
These can be viewed by configuring
logging:
level:
io.micrometer: debug
> GPC-NONE: change log level for metrics to debug

- build.gradle.kts
Think this comment got detached during a rejig of dependencies, but this should make things clearer
> GPC-NONE: Clarify build.gradle labelling

- src/main/kotlin/uk/gov/gdx/datashare/config/ResourceServerConfiguration.kt
Needed for autogenerating sections of documentation: https://tdt-documentation.london.cloudapps.digital/write_docs/add_openapi_spec/#convert-an-openapi-specification-into-documentation
> GPC-117: Expose yaml openapi spec

- src/main/kotlin/uk/gov/gdx/datashare/services/ScheduledJobService.kt
I think this is the problem with the UnconsumedEvents count, where when Micrometer is gathering metrics, there's no value available (the gauge itself doesn't really hold the value)
> GPC-NONE: shuffle gauge configuration to persist value between calls

- terraform/dev/main.tf
- terraform/modules/security_hub/main.tf
- terraform/modules/security_hub/variables.tf
- terraform/shared/main.tf
We probably need to do something about getting notifications of outputs, and should discuss which standards we want to follow, but the CIS standard is a generally broad reaching and sensible baseline
> GPC-248: Enable Security Hub

- terraform/modules/data-share-service/ec2.tf
Now that we're using privatelink and SSM I don't think we need these EIPs
> GPC-NONE: Remove public IP from bastion hosts

- terraform/modules/data-share-service/cloudfront.tf
Reverts alphagov/gdx-data-share-poc#719 whilst I figure out why this doesn't work
> Revert "GPC-250: Enable Shield Advanced on CloudFront"

- terraform/modules/bootstrap/bootstrap.tf
- terraform/modules/data-share-service/s3.tf
- terraform/modules/grafana/cloudfront-logs.tf
- terraform/modules/s3/logs_bucket.tf
- terraform/modules/s3/main.tf
To fix https://eu-west-2.console.aws.amazon.com/securityhub/home?region=eu-west-2#/standards/cis-aws-foundations-benchmark-1.4.0/S3.5
> GPC-NONE: Deny insecure transport to buckets

- terraform/modules/data-share-service/ec2.tf
- terraform/modules/data-share-service/vpc.tf
- terraform/shared/main.tf
Note that this is a quick fix for the security hub finding - but we might want to think more about how open our acls are, as we were just using the default rules that allows traffic on all ports
> GPC-277: Lock down network ACLs

- src/main/resources/application.yml
- terraform/modules/data-share-service/ecs.tf
Looks like this can't be set using this style of config
> GPC-NONE: Ignore missing xray context

- terraform/modules/data_share_service/lb.tf
I've been meaning to do this for a while, but https://github.com/alphagov/digital-identity-architecture/pull/438 reminded me
> GPC-NONE: Add security.txt redirect

- terraform/modules/data_share_service/cloudfront.tf
This change has the following effects:
- Change cognito user pool admin client permitted callback url to the `service.gov.uk` version
- Change `SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL` env var to `service.gov.uk` version
- Change len lambdas to point at `service.gov.uk` domain
- Change gro lambdas to point as `service.gov.uk` domain
> GPC-371: Use service domain

- grafana/.trivyignore
- prometheus/.trivyignore
As this issue does not affect non-empty associated data authentication and we expect it to be rare for an application to use empty associated data entries this is qualified as Low severity issue.
Does not affect us.
> GPC-470: Suppress CVE-2023-2975

- stack-orchestration/configuration/build/vpc/parameters.json
- stack-orchestration/configuration/dev/vpc/parameters.json
- stack-orchestration/configuration/integration/vpc/parameters.json
- stack-orchestration/configuration/production/vpc/parameters.json
- stack-orchestration/configuration/staging/vpc/parameters.json
Cognito integration requires access from lambdas through the VPC to the relevant cognito idp url. This is not provided by an AWS VPC endpoint, so we have to configure both AllowedDomains and AllowRules in our VPC stack
> GPC-NONE: Add allow rules to VPC

- template.yaml
AWS::Logs::LogGroup property KmsKeyId does not take the Key ID, it takes the Key ARN, updated to reflect that
> GPC-NONE: Fix KMS Key ID to be ARN

- ci/appspec-template.json
`appspec-template.json` got deleted when I was removing security hub, this PR adds it back in to fix our failing deployments to the old service
> GPC-NONE: Add appspec back into ci folder

- template.yaml
As part of aligning observability with DI, we should be piping all of our non development logs to CSLS
> GPC-510: Pipe logs to CSLS

- template.yaml
Removes unnecessary quotes, and replaces single quotes with double. This is to keep consistency across the whole template
> GPC-NONE: Tidy cloudformation template

- groIngestionStepFunction.asl.json
This is to make sure our failure delete json records step gets the input of the map which includes its buckets name and file key.
> GPC-NONE: Update error catching to include input in output

- .github/workflows/scheduled-trivy-scan.yml
- .github/workflows/trivy.yml
Update trivy to not scan cloudformation files already scanned by checkov
> GPC-NONE: Update trivy skip

- .cfnlintrc.yaml
- README.md
- sam/deathAcquirerTemplate.yaml
- samconfig.toml
- template.yaml
This allows for more resources and also allows for a nicer separation of our templates from one horrible file
> GPC-NONE: Split template into multiple applications to allow for more resources

- lambdas/gro-convert-to-json/src/test/java/uk/gov/di/data/lep/ConvertToJsonTest.java
- lambdas/gro-publish-record/src/main/java/uk/gov/di/data/lep/PublishRecord.java
- lambdas/gro-publish-record/src/test/java/uk/gov/di/data/lep/PublishRecordTest.java
- lib/src/main/java/uk/gov/di/data/lep/library/dto/GroAddressStructure.java
- lib/src/main/java/uk/gov/di/data/lep/library/dto/GroJsonRecord.java
- lib/src/main/java/uk/gov/di/data/lep/library/dto/GroPersonNameStructure.java
- lib/src/main/java/uk/gov/di/data/lep/library/dto/PersonBirthDateStructure.java
- lib/src/main/java/uk/gov/di/data/lep/library/dto/PersonDeathDateStructure.java
- lib/src/main/java/uk/gov/di/data/lep/library/services/AwsService.java
- lib/src/test/java/uk/gov/di/data/lep/library/services/AwsServiceTest.java
The JsonProperty annotations doesn't work for Lambda mapping of input (so RegistrationID was not being parsed into registrationID when the PublishRecord lambda function was hit). As a result, we have updated the xml to json mapping to map to the lowercase and pluralised version of the JSON.
We also had incorrect permissions in the AWS service for our credentials provider
> GPC-NONE: Fix Permissions and Gro Json Record properties

- template.yaml
Have added the dlq to the policy. Seems that the warning persists (even though it works) but this is rectified by changing the policy statement - see: https://stackoverflow.com/questions/63707792/how-to-add-a-redrive-policy-to-an-sns-with-an-encrypted-dlq
> GPC-612: Fix dlq policy warning

- scripts/update-rfc-techdocs.sh
- techdocs/source/data-model.html.md.erb
Bring in the additional RFCs so anyone reading has more context on the entire data model. This means we have a public reference for the 'name' structure and the 'address' structure also.
Plus some messing to allow running the script on a local architecture repo checkout again.
> Extra RFCs

- lambdas/.trivyignore
- lib/.trivyignore
Not looked at this in much detail yet, but there doesn't appear to be a fix available yet through the AWS dependencies that pull this in
> GPC-646: Ignore potential vulnerability
