govuk-one-login/life-events-platform

- doc/architecture/decisions/0003-gdx-death-notification-event.md
- doc/architecture/decisions/0004-baseline-aws-infrastructure.md
thought it was worth documenting the initial discussion around e.g. ECS and other services
> doc: add ADR for initial infrastructure

- .github/workflows/terraform-shared.yml
Remove redundant plan checking as we do not halt after plan anyways
> chore: Remove redundant plan checking

- .github/workflows/application.yml
- .github/workflows/build-and-push.yml
- .github/workflows/terraform-shared.yml
Decrease the amount of docker build steps
> chore: Decrease the amount of docker build steps

- terraform/modules/data-share-service/ecs.tf
- terraform/modules/data-share-service/sns.tf
- terraform/modules/sns/main.tf
- terraform/modules/sns/outputs.tf
- terraform/modules/sns/variables.tf
> feat: add SNS topic and roles

- terraform/modules/data-share-service/ecs.tf
- terraform/modules/data-share-service/sqs.tf
- terraform/modules/sqs/main.tf
- terraform/modules/sqs/outputs.tf
- terraform/modules/sqs/variables.tf
> feat:  Add initial SQS queues

- .github/workflows/terraform-shared.yml
> feat: Fail job if plan fails

- CONTRIBUTING.md
Something to flesh out as we go, so this is very much a WIP, but felt worth spinning it up
> feat: Add initial contributing guide

- terraform/modules/data-share-service/ecs.tf
- terraform/modules/data-share-service/kms.tf
- terraform/modules/data-share-service/rds.tf
Resolves #33, but as with SNS/SQS, I think we'll probably want to dive into using IAM/equivalents over this direct password passing
> feat: Add first pass at RDS configuration for POC

- terraform/modules/cognito/main.tf
- terraform/modules/cognito/outputs.tf
- terraform/modules/cognito/variables.tf
- terraform/modules/data-share-service/cognito.tf
- terraform/modules/data-share-service/ecs.tf
> feat: Add initial cognito configuration

- src/main/kotlin/uk/gov/gdx/datashare/config/OpenApiConfiguration.kt
- terraform/modules/cognito/main.tf
- terraform/modules/cognito/variables.tf
- terraform/modules/data-share-service/cognito.tf
> feat: Swagger cognito

- src/main/kotlin/uk/gov/gdx/datashare/repository/ConsumerSubscription.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/ConsumerSubscriptionRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventData.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventDataRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventType.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventTypeRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/IngressEventData.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/IngressEventDataRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/IngressEventType.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/IngressEventTypeRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/DataProcessor.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/DataShareTopicService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventCleanup.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventDataRetrievalService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventPollService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/SubscriptionManagerService.kt
- src/main/resources/db/devonly/V9_1__dev_data.sql
- src/main/resources/db/migration/V1_6__ingress_and_egress_events.sql
Splits ingress and egress events and adds mapping with 0 change between them
> Separate ingress and egress events

- src/main/kotlin/uk/gov/gdx/datashare/repository/ConsumerSubscriptionRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventDataRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/repository/EgressEventTypeRepository.kt
- src/main/kotlin/uk/gov/gdx/datashare/resource/EventsController.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventDataRetrievalService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventDataService.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventPollService.kt
> feat: Add events status

- doc/architecture/decisions/0004-baseline-aws-infrastructure.md
- doc/architecture/decisions/0005-queue-api.md
Closes #35 in favour of an ADR for the interface
> docs: Add Queue API as a ADR

- .editorconfig
- .gitignore
- build.gradle.kts
This is a starter to getting towards Spring Boot 3, and slightly simplifying the total set of dependencies
> feat: Simplify spring dependencies

- build.gradle.kts
- src/main/kotlin/uk/gov/gdx/datashare/config/DatabasePropertiesListener.kt
- src/main/kotlin/uk/gov/gdx/datashare/config/R2dbcConfig.kt
- src/main/kotlin/uk/gov/gdx/datashare/config/RdsIAMHikariDataSource.kt
- src/main/kotlin/uk/gov/gdx/datashare/config/ShedlockConfiguration.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/DbCredentialsService.kt
- src/main/resources/META-INF/spring.factories
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/gdx/datashare/helper/TestBase.kt
- src/test/resources/application-test.yml
- terraform/modules/data-share-service/ecs.tf
- terraform/modules/data-share-service/iam.tf
- terraform/modules/data-share-service/rds.tf
https://trello.com/c/wX8mhgGI/33-prefer-iam-over-secrets-for-rds-sqs-etc
I've made changes to R2DBC for the main application and JDBC for shedlock and flyway. Those are the only things I'm aware of that interact with the database. 
I've made the assumption that flyway will not need a connection for more than 15 minutes after app boot, which seems fairly safe.
Some of this is a fair bit more manual than springboot might like, but I've done my best to make it (hopefully) pretty seamless so long as you don't look too closely
> Use IAM credentials for RDS database

- build.gradle.kts
- src/main/kotlin/uk/gov/gdx/datashare/queue/AwsQueueService.kt
- src/main/kotlin/uk/gov/gdx/datashare/queue/SqsConfiguration.kt
- src/test/kotlin/uk/gov/gdx/datashare/queue/AwsQueueServiceTest.kt
This is the only place it's used and I'm not sure it's necessary
> chore: Remove gson dependency

- src/main/kotlin/uk/gov/gdx/datashare/controller/EventsController.kt
- src/main/kotlin/uk/gov/gdx/datashare/service/EventDataService.kt
- src/test/kotlin/uk/gov/gdx/datashare/controller/EventsControllerTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/service/EventDataServiceTest.kt
- terraform/modules/cloudwatch_dashboard/main.tf
- terraform/modules/cloudwatch_dashboard/variables.tf
- terraform/modules/data-share-service/cloudwatch.tf
https://trello.com/c/bjLGFOYL/29-metrics-for-dashboarding
Adding these metrics first, then will add to terraform
> Further metrics

- terraform/modules/cloudwatch_dashboard/main.tf
Flatten was applied on wrong level of nesting
> Fix further metrics

- .editorconfig
- .github/workflows/kotlin-lint-fix.yml
- build.gradle.kts
Vaguely related to the terraform stuff, this is some thoughts on Kotlin linting
We've got inconsistency in the trailing comma rule, which may or may not cause a fight - I'm easy either way...
> housekeeping:  Ktlint

- terraform/dev/main.tf
- terraform/modules/consumer/get-event.tf
- terraform/modules/consumer/get-events.tf
- terraform/modules/consumer/lambdas/get_event.py
- terraform/modules/consumer/lambdas/get_events.py
- terraform/modules/consumer/main.tf
- terraform/modules/consumer/variables.tf
- terraform/modules/lambdas/common.py
- terraform/modules/len/lambdas/len.py
- terraform/modules/len/main.tf
Get an event from the datashare API and validate the fields against the LEV API. I intend to add CW metrics and dashboarding for this, but that will come later
> Get event lambda

- docker-compose.yml
- Set defaults for hostname so it works out the box
- Add entries for host-style S3 buckets
> fix: Fixes for localstack configuration

- terraform/modules/consumer/cloudwatch.tf
- terraform/modules/consumer/delete-event.tf
- terraform/modules/consumer/get-event.tf
- terraform/modules/consumer/get-events.tf
- terraform/modules/consumer/lambdas/delete_event.py
- terraform/modules/consumer/lambdas/get_event.py
- terraform/modules/consumer/lambdas/get_events.py
- terraform/modules/data-share-service/cloudwatch.tf
- terraform/modules/lambdas/common.py
> feat: Add metrics dashboard for example consumer

- terraform/modules/data-share-service/subscription.tf
This is an over simplification of the subscription policy and up for discussion!
> add terraform subscriptions for topics 

- Dockerfile
Seeing errors like image when connecting to database.  Not sure this is the fix, but it looks promising
> fix: add RDS cert to truststore

- src/main/kotlin/uk/gov/gdx/datashare/services/EventDataService.kt
Do not make one call per event to fetch enrichment fields
> GPC-NONE: Fix n+1 query on enrichment fields

- terraform/modules/consumer/lambdas/get_event.py
- terraform/modules/consumer/stepfunction.tf
- retry on timeout
- Accept null values
> Update consumer stepfunction

- terraform/modules/data-share-service/deploy_hook.tf
- terraform/modules/data-share-service/github_iam.tf
- terraform/modules/deploy_hook/lambdas/hook.py
- terraform/modules/deploy_hook/main.tf
- terraform/modules/deploy_hook/variables.tf
Fix deploy hook, always succeed even if code throws
> GPC-NONE: Fix deploy hook

- src/main/resources/logback-spring.xml
https://logback.qos.ch/codes.html#layoutInsteadOfEncoder
> GPC-NONE: Update logback config

- terraform/modules/deploy_hook/lambdas/hook.py
> GPC-93: Add in deploy hook check

- src/test/kotlin/uk/gov/gdx/datashare/queue/AwsQueueServiceTest.kt
Small drive-by refactor to replace in one place Mockito with MockK, which we use in most of the codebase.
We've got a couple of other inherited files still using Mockito so can't remove the dependency right now, but wanted to see how plausible this was
> GPC-NONE: Replace Mockito with Mockk

- LICENCE
- README.md
https://gds-way.cloudapps.digital/manuals/licensing.html
> GPC-NONE: Add licence

- src/main/kotlin/uk/gov/gdx/datashare/config/WebClientConfiguration.kt
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.http-clients
> GPC-NONE: autowire client builder to enable metrics

- src/main/kotlin/uk/gov/gdx/datashare/controllers/EventsController.kt
This was only broken through swagger
> GPC-NONE: Add status code and fix response type of delete

- doc/how-to-onboard-a-supplier.md
This effectively covers off the question in GPC-112 but in a slightly clearer place
> GPC-NONE: Add starter for supplier onboarding

- Dockerfile
Part 1 of GPC-151 is to use Corretto, I want to check this works nicely / boots up properly, then will try playing with SSL config
> GPC-151: Use corretto for Java distribution

- terraform/modules/data-share-service/ecs.tf
This builds on #55, but I want to check it works as Corretto first
> GPC-151: Set Postgres to verify-full

- terraform/modules/data-share-service/ecs.tf
Reverts alphagov/gdx-data-share-poc#554
> GPC-151: Revert set Postgres to verify-full

- src/main/kotlin/uk/gov/gdx/datashare/controllers/BaseDataController.kt
- src/main/kotlin/uk/gov/gdx/datashare/controllers/EventsController.kt
These 406s are provided by the OpenApiConfiguration file
> GPC-NONE: Remove unnecessary 406

- grafana/Dashboards/Error Rates.json
> GPC-181: Add error rates dashboard

- doc/architecture/decisions/0015-monitoring.md
- doc/architecture/decisions/0016-push-directly-to-sqs.md
> GPC-187: ADR for SQS

- src/main/kotlin/uk/gov/gdx/datashare/controllers/EventsController.kt
> GPC-NONE: fix formatting of techdoc

- doc/architecture/decisions/0018-data-flows.md
This is very much for discussion
> GPC-199: Additional data flows ADR

- src/main/kotlin/uk/gov/gdx/datashare/enums/Gender.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/DeathNotificationDetails.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/EventNotification.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/PrisonerDetails.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/TestEventDetails.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/DeathNotificationService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/EnrichmentService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/EventDataService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/PrisonerLookupService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/TestEventEnrichmentService.kt
- src/test/kotlin/uk/gov/gdx/datashare/models/DeathNotificationDetailsTest.kt
Just some small changes to add some types and make things a little more consistent. This will make my SQS work easier
> GPC-NONE: commonise event details

- frontend/package-lock.json
- frontend/package.json
- frontend/server/config.ts
- frontend/server/controllers/acquirerController.ts
- frontend/server/data/gdxDataShareClient.ts
- frontend/server/data/restClient.ts
- frontend/server/middleware/setupStaticResources.ts
- frontend/server/routes/index.ts
- frontend/server/sanitisedError.ts
- frontend/server/views/pages/addAcquirerForm.njk
- frontend/server/views/pages/index.njk
- frontend/server/views/pages/success.njk
A basic acquirer management that runs locally but is not authenticated or hosted
> GPC-101 Acquirer management UI

- terraform/shared/modules/grafana/cognito.tf
> GPC-NONE: Fix verify message

- terraform/demo/main.tf
- terraform/dev/main.tf
- terraform/modules/data-share-service/main.tf
- terraform/modules/data-share-service/rds.tf
- terraform/modules/data-share-service/vpc.tf
This reverts commit bf6ece3d3a4e2db903a4dc8a82714f177c3f4800.
> Revert "GPC-211: Add multi region data backups (#621)"

- build.gradle.kts
> GPC-NONE: Update Springdoc dependencies

- .trivyignore
https://avd.aquasec.com/nvd/2023/cve-2023-0464/
> GPC-NONE: Silence trivy

- terraform/modules/data-share-service/deploy_hook.tf
- terraform/modules/data-share-service/ec2.tf
- terraform/modules/data-share-service/ecs-security.tf
- terraform/modules/data-share-service/ecs.tf
- terraform/modules/data-share-service/lb-security.tf
- terraform/modules/data-share-service/lb.tf
- terraform/modules/data-share-service/rds.tf
- terraform/modules/data-share-service/vpc.tf
- terraform/modules/s3/main.tf
- terraform/modules/s3/variables.tf
- terraform/modules/vpc/main.tf
- terraform/modules/vpc/outputs.tf
- terraform/modules/vpc/variables.tf
- terraform/shared/main.tf
Update VPC into its own module and fix flow logs
> GPC-NONE: Update vpc

- terraform/modules/gro_ingestion_service/lambdas/.eslintrc.json
- terraform/modules/gro_ingestion_service/lambdas/package-lock.json
- terraform/modules/gro_ingestion_service/lambdas/package.json
- terraform/modules/gro_ingestion_service/lambdas/src/functions/publish-event.function.ts
- terraform/modules/gro_ingestion_service/lambdas/src/functions/test.function.ts
- terraform/modules/gro_ingestion_service/lambdas/src/index.ts
- terraform/modules/gro_ingestion_service/lambdas/src/models/EventRecord.ts
- terraform/modules/gro_ingestion_service/lambdas/src/models/PublishEvent.ts
This adds the code for the stream lambda function, but does not add the infrastructure changes, those will be in a further PR
> GPC-349: Stream DynamoDB records to GDX API

- terraform/modules/iam_user_roles/main.tf
- terraform/modules/iam_user_roles/variables.tf
- terraform/shared/main.tf
Permissions required for running a terraform plan
> GPC-NONE: Add permissions to read only roles

- terraform/modules/dwp_dev/main.tf
- terraform/modules/sqs/outputs.tf
Per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#Principal_specifying
> GPC-336: Use condition to specify role arn

- terraform/modules/policies/alternate_accounts.tf
Will wait for a number to be added into ssm before I merge this
> GPC-NONE: Add security account

- doc/infrastructure.md
- doc/investigating-in-aws.md
- terraform/modules/cloudtrail/athena.tf
This is already applied because it was hideously complicated and there was no chance of me getting it right the first time around
> GPC-NONE: CloudTrail in athena

- src/main/kotlin/uk/gov/gdx/datashare/models/AcquirerSubRequest.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/validators/SingleConsumptionMethod.kt
- src/main/kotlin/uk/gov/gdx/datashare/models/validators/SingleConsumptionMethodValidator.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/AcquirerEventProcessor.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/AcquirersService.kt
- src/main/kotlin/uk/gov/gdx/datashare/services/OutboundEventQueueService.kt
- src/test/kotlin/uk/gov/gdx/datashare/models/AcquirerSubRequestTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/AcquirerEventProcessorTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/AcquirersServiceTest.kt
- src/test/kotlin/uk/gov/gdx/datashare/services/OutboundEventQueueServiceTest.kt
I've not made the change to /admin in this one to keep the review smaller
> GPC-383: API ability to create acquirer queues

- terraform/modules/data_share_service/vpc.tf
- terraform/modules/vpc/main.tf
- terraform/modules/vpc/variables.tf
- terraform/shared/main.tf
There's a chance that this will break something, but it should be obvious fairly quickly
> GPC-300: Restrict VPC ACLs

- terraform/modules/cognito/waf.tf
Per https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-totp.html#hosted-ui-totp-waf (ish)
> GPC-272: Allow 2fa requests through WAF

- platform/src/main/kotlin/uk/gov/gdx/datashare/config/ApiExceptionHandler.kt
- platform/src/main/kotlin/uk/gov/gdx/datashare/enums/EnrichmentField.kt
- platform/src/main/kotlin/uk/gov/gdx/datashare/enums/EventType.kt
- platform/src/main/kotlin/uk/gov/gdx/datashare/services/AcquirersService.kt
- platform/src/test/kotlin/uk/gov/gdx/datashare/services/AcquirersServiceTest.kt
Hannah's changes from https://github.com/alphagov/di-data-life-events-platform/pull/1459
> Gpc 162 enrichment field event type relationship

- terraform/demo/main.tf
DWP will now be using this environment in addition to dev
> GPC-440: Data in demo

- .github/workflows/sam-main.yml
- .github/workflows/test.yml
Update and specify role session
> GPC-NONE: Update configure-aws-credentials actions

- template.yaml
Update key name and add delivery dlq
> GPC-NONE: Update key name

- template.yaml
The previous bucket name was used, update the name
> GPC-NONE: Update bucket name to something unused

- groIngestionStepFunction.asl.json
- template.yaml
> GPC-495: Delete S3 Files automatically in step function

- template.yaml
Updates the step function policy to limit and allow S3 to delete
> GPC-NONE: Update step function policy

- stack-orchestration/configuration/build/sam-deploy-pipeline/parameters.json
- stack-orchestration/configuration/build/vpc/parameters.json
- stack-orchestration/configuration/dev/vpc/parameters.json
- stack-orchestration/configuration/integration/vpc/parameters.json
- stack-orchestration/configuration/production/vpc/parameters.json
- stack-orchestration/configuration/staging/vpc/parameters.json
Update to allow auth domains and reduce allowed accounts for build pipeline as the max is 2
> GPC-NONE: Update stack orchestration

- lambdas/death-enrichment/src/main/java/uk/gov/di/data/lep/GroDeathEnrichment.java
- lambdas/death-enrichment/src/test/java/uk/gov/di/data/lep/GroDeathEnrichmentTest.java
- lambdas/death-minimisation/src/main/java/uk/gov/di/data/lep/GroDeathMinimisation.java
- lambdas/death-minimisation/src/test/java/uk/gov/di/data/lep/GroDeathMinimisationTest.java
- lambdas/death-validation/src/test/java/uk/gov/di/data/lep/GroDeathValidationTest.java
- template.yaml
1. Make public method private
2. Rename GroDeathNotificationMinimisation to GroDeathMinimisation to keep all functions in line
3. Update exception to more specific exception in test
> GPC-NONE: Minor tidying

- template.yaml
[PLAT-2133](https://govukverify.atlassian.net/browse/PLAT-2133)
[PLAT-2133]: https://govukverify.atlassian.net/browse/PLAT-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GPC-NONE: Comment out schedule until secure pipelines roles improved

- README.md
There are a few different options, happy with a different selection if you prefer: https://sonarcloud.io/project/information?id=alphagov_di-data-life-events-platform
> Add Sonar badges

- lambdas/gro-convert-to-json/src/main/java/uk/gov/di/data/lep/ConvertToJson.java
- lambdas/gro-convert-to-json/src/main/java/uk/gov/di/data/lep/dto/DeathRegistrationGroup.java
- lib/src/testFixtures/java/uk/gov/di/data/lep/library/dto/GroDeathEventEnrichedDataBuilder.java
- don't expose a public field
- convert a class to a record
> GPC-NONE: minor code style fixes

- techdocs/source/acquirer-onboarding.html.md.erb
Document permissions needed for acquirer role
> GPC-NONE: Update acquirer onboarding docs

- stack-orchestration/configuration/build/vpc/parameters.json
- stack-orchestration/configuration/dev/vpc/parameters.json
- stack-orchestration/configuration/integration/vpc/parameters.json
- stack-orchestration/configuration/production/vpc/parameters.json
- stack-orchestration/configuration/staging/vpc/parameters.json
These rules are covered by default rules (for access to *.account.gov.uk)
> GPC-NONE: Remove unnecessary suricata rules

- techdocs/source/release-management.html.md.erb
Starter of release management documentation
> GPC-544: Create release-management.html.md.erb

- techdocs/source/release-management.html.md.erb
> GPC-544: Release management draft

- template.yaml
Add tags to data stores to indicate if they store PII/sensitive data
> GPC-563: Add sensitive data tags

- techdocs/source/schema.html.md.erb
We should wait until https://github.com/alphagov/di-identity-vocab/pull/44 is merged for this
> GPC-591: Point to latest schema versions

- techdocs/source/slos-slas.html.md.erb
Extend the latency SLO to 5m as this is more achievable
> GPC-NONE: Extend latency SLO

- lambdas/gro-pull-file/src/main/java/uk/gov/di/data/lep/GroPullFile.java
PR so that we can see the resources in the bucket in logs for prod testing
> GPC-580: Log resources in bucket

- template.yaml
This enables our Dynatrace monitoring to work
> GPC-614: Move Lambdas to protected subnet

- techdocs/source/schema.html.md.erb
> GPC-NONE: Update links in schema.html.md.erb

- techdocs/Gemfile.lock
- techdocs/source/data-retention-policy.html.md.erb
From https://docs.google.com/document/d/1ga7HXf5TONVGgRRwq5kowJfxwkiAIyHQxhWvQw5aYms/edit#heading=h.p6d6vsvn6j7y
> GPC-480: Update data retention policy

- .github/workflows/lint.yml
See https://github.com/alphagov/di-data-life-events-platform/actions/runs/6351148414/job/17251902531?pr=2336
> GPC-NONE: Fix auto linting

- template.yaml
Also some minor changes to other parts for consistency
> GPC-643: Enforce TLS version 1.2 or higher
